Repository ikshvaku01/DSA, pull requests merged in 2022-10, with the labels that each got.

#3 updated the README.md
  README.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#10 new commit
  C++ NOTES/CPP_FUNCTIONS.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#16 Codechef
  REPOSITORY/QUESTIONS LIBRARY/COMPETITIVE CODING/CODECHEF/0000-1000 Beginner Level/BALLBOX.CPP
  REPOSITORY/QUESTIONS LIBRARY/COMPETITIVE CODING/CODECHEF/0000-1000 Beginner Level/BALLBOX.md
  REPOSITORY/QUESTIONS LIBRARY/COMPETITIVE CODING/CODECHEF/0000-1000 Beginner Level/BROKENPHONE.CPP
  REPOSITORY/QUESTIONS LIBRARY/COMPETITIVE CODING/CODECHEF/0000-1000 Beginner Level/BROKENPHONE.md
  REPOSITORY/QUESTIONS LIBRARY/COMPETITIVE CODING/CODECHEF/0000-1000 Beginner Level/CBSPEED.CPP
  REPOSITORY/QUESTIONS LIBRARY/COMPETITIVE CODING/CODECHEF/0000-1000 Beginner Level/CBSPEED.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#18 inorder and preorder traversal of binary tree
  DATA STRUCTURE AND ALGORITHM/inorder_traversal.md
  DATA STRUCTURE AND ALGORITHM/preorder_traversal.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#17 binary tree inorder and preorder traversal in both recursive and iter…
  DATA STRUCTURE AND ALGORITHM/Binary_tree/a.out
  DATA STRUCTURE AND ALGORITHM/Binary_tree/inorder_traversal.cpp
  DATA STRUCTURE AND ALGORITHM/Binary_tree/preorder_traversal.cpp
Labels: documentation, good first issue, hacktoberfest

#24 Cpp notes of Arrays.
  C++ NOTES/ARRAYS.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#23 created binary_search.md
  DATA STRUCTURE AND ALGORITHM/binary_search.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#19 Added Sieve Of Eratosthenes Algorithm
  DATA STRUCTURE AND ALGORITHM/SIEVE_OF_ERATOSTHENES.cpp
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#7 Create DATA_TYPES.md
  C++ NOTES/DATA_TYPES.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#29 Create bubbleSort_ascen.java
  DATA STRUCTURE AND ALGORITHM/bubbleSort_ascen.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#30 Adding a Leetcode Hard Question
  REPOSITORY/QUESTIONS LIBRARY/COMPETITIVE CODING/LEETCODE/MEDIUM/Trapping Rain Water.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#34 Adding a Jump game Question
  REPOSITORY/QUESTIONS LIBRARY/COMPETITIVE CODING/LEETCODE/MEDIUM/Jump Game.md
Labels: documentation, hacktoberfest
